spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/moayoeats
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}


  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  thymeleaf:
    cache: false
    suffix: .html
#    prefix: src/main/resources/templates/

jwt:
  secret:
    key: ${JWT_SECRET_KEY}